#!/usr/bin/env python3
"""Context Image Harvester

Collects real-photo candidates for a list of prompts from Pexels, SerpApi
(Google Images / Bing Images), and Wikimedia Commons. It globally removes exact
and perceptual near-duplicates, rejects obvious AI/art/vector metadata, creates
16:10 review images, keeps resized source copies, writes manifests/contact sheet,
and builds a ZIP archive.

The script does NOT guarantee that every discovered web image is licensed for
your intended use. Pexels and Wikimedia include provenance/license metadata;
SerpApi results must be rights-checked at the source page.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import html
import io
import json
import os
import re
import shutil
import sys
import time
import zipfile
from pathlib import Path

import imagehash
import requests
from PIL import Image, ImageOps

DEFAULT_TIMEOUT = 35
DEFAULT_UA = os.getenv(
    "WIKIMEDIA_USER_AGENT",
    "ContextImageHarvester/1.0 (https://github.com/AfolJvsh/context-image-harvester; contact via GitHub)",
)

AI_TERMS = {
    "ai generated", "ai-generated", "generated by ai", "generative ai",
    "midjourney", "stable diffusion", "dall-e", "dall·e", "firefly",
    "leonardo ai", "flux ai", "synthetic image", "prompt-generated",
}
NONPHOTO_TERMS = {
    "illustration", "vector", "digital art", "3d render", "cgi", "drawing",
    "painting", "clipart", "diagram", "logo", "icon", "poster", "cartoon",
}


def clean(value) -> str:
    text = html.unescape(str(value or ""))
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def slug(text: str, limit: int = 64) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return value[:limit].rstrip("-") or "image"


def load_items(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("prompts") or data.get("items") or []
    if not isinstance(data, list):
        raise SystemExit("Prompt file must be a JSON list, or an object containing 'prompts'/'items'.")

    items = []
    for idx, item in enumerate(data, start=1):
        if isinstance(item, str):
            prompt = clean(item)
            name = f"Prompt {idx}"
            item_id = idx
        elif isinstance(item, dict):
            prompt = clean(item.get("prompt") or item.get("search_query") or item.get("query"))
            name = clean(item.get("name") or item.get("service") or item.get("title") or f"Prompt {idx}")
            item_id = int(item.get("id", idx))
        else:
            continue
        if prompt:
            items.append({"id": item_id, "name": name, "prompt": prompt})

    if not items:
        raise SystemExit("No valid prompts found.")
    return items


def short_query(item: dict) -> str:
    stop = {
        "professional", "real", "photography", "photograph", "editorial", "modern",
        "using", "with", "and", "the", "a", "an", "of", "on", "in", "at", "for",
        "or", "from", "performing", "reviewing", "working", "workplace", "business",
    }
    words: list[str] = []
    for word in re.findall(r"[a-z0-9]+", (item["name"] + " " + item["prompt"]).lower()):
        if len(word) > 2 and word not in stop and word not in words:
            words.append(word)
    return " ".join(words[:8]) or item["name"]


class Harvester:
    def __init__(
        self,
        output: Path,
        per_item: int = 8,
        per_provider: int = 25,
        phash_distance: int = 8,
        serpapi_max: int = 110,
        max_download_mb: int = 25,
        timeout: int = DEFAULT_TIMEOUT,
    ):
        self.output = output
        self.per_item = per_item
        self.per_provider = per_provider
        self.phash_distance = phash_distance
        self.serpapi_max = serpapi_max
        self.max_download_bytes = max_download_mb * 1024 * 1024
        self.timeout = timeout

        self.serpapi_used = 0
        self.wikimedia_requests = 0
        self.wikimedia_blocked_until = 0.0
        self.last_wikimedia_request = 0.0

        self.images_dir = self.output / "images"
        self.sources_dir = self.output / "source_originals"
        self.images_dir.mkdir(parents=True, exist_ok=True)
        self.sources_dir.mkdir(parents=True, exist_ok=True)

        self.used_sha: set[str] = set()
        self.used_phash: list[imagehash.ImageHash] = []
        self.records: list[dict] = []

        self.session = requests.Session()
        self.session.headers.update({"User-Agent": DEFAULT_UA, "Accept-Encoding": "gzip, deflate"})
        self.pexels_key = os.getenv("PEXELS_API_KEY", "").strip()
        self.serpapi_key = os.getenv("SERPAPI_API_KEY", "").strip()

    def pexels(self, item: dict) -> list[dict]:
        if not self.pexels_key:
            return []
        response = self.session.get(
            "https://api.pexels.com/v1/search",
            params={"query": item["prompt"], "per_page": min(self.per_provider, 80)},
            headers={"Authorization": self.pexels_key, "User-Agent": DEFAULT_UA},
            timeout=self.timeout,
        )
        response.raise_for_status()
        out = []
        for photo in response.json().get("photos", []):
            src = photo.get("src") or {}
            image_url = src.get("large2x") or src.get("large") or src.get("original")
            if not image_url:
                continue
            out.append({
                "provider": "pexels",
                "title": clean(photo.get("alt")) or f"Pexels photo {photo.get('id', '')}",
                "description": clean(photo.get("alt")),
                "image_url": image_url,
                "page_url": photo.get("url", ""),
                "creator": clean(photo.get("photographer")),
                "license": "Pexels License",
                "license_url": "https://www.pexels.com/license/",
            })
        return out

    def serpapi(self, engine: str, item: dict) -> list[dict]:
        if not self.serpapi_key or self.serpapi_used >= self.serpapi_max:
            return []

        self.serpapi_used += 1
        params = {"engine": engine, "api_key": self.serpapi_key, "q": item["prompt"]}
        if engine == "google_images":
            params.update({"safe": "active", "num": min(self.per_provider, 100)})
            provider = "serpapi-google"
        else:
            params.update({"safeSearch": "Strict", "count": min(self.per_provider, 100), "mkt": "en-US"})
            provider = "serpapi-bing"

        try:
            response = self.session.get("https://serpapi.com/search.json", params=params, timeout=self.timeout)
            response.raise_for_status()
            data = response.json()
        except Exception as exc:
            print(f"[warn] SerpApi {engine} failed for {item['name']}: {exc}", file=sys.stderr)
            return []

        out = []
        for result in data.get("images_results", []):
            image_url = result.get("original") or result.get("thumbnail")
            if not image_url:
                continue
            out.append({
                "provider": provider,
                "title": clean(result.get("title")),
                "description": clean(result.get("source")),
                "image_url": image_url,
                "page_url": result.get("link") or result.get("source") or "",
                "creator": "",
                "license": "Verify source rights",
                "license_url": "",
            })
        return out

    def _wikimedia_get(self, params: dict) -> dict | None:
        now = time.time()
        if now < self.wikimedia_blocked_until:
            return None

        elapsed = now - self.last_wikimedia_request
        if elapsed < 2.0:
            time.sleep(2.0 - elapsed)

        params = dict(params)
        params["maxlag"] = 5

        for attempt in range(3):
            self.last_wikimedia_request = time.time()
            self.wikimedia_requests += 1
            try:
                response = self.session.get(
                    "https://commons.wikimedia.org/w/api.php",
                    params=params,
                    timeout=self.timeout,
                )
            except requests.RequestException as exc:
                time.sleep(4 * (2 ** attempt))
                print(f"[wiki] network error: {exc}", file=sys.stderr)
                continue

            if response.status_code in (429, 503):
                raw = response.headers.get("Retry-After", "").strip()
                try:
                    retry_after = max(1, int(raw))
                except ValueError:
                    retry_after = 15 * (2 ** attempt)
                self.wikimedia_blocked_until = time.time() + retry_after
                print(
                    f"[wiki] HTTP {response.status_code}; cooldown {retry_after}s. Skipping Commons until cooldown expires.",
                    file=sys.stderr,
                )
                return None

            try:
                response.raise_for_status()
                data = response.json()
            except Exception as exc:
                time.sleep(4 * (2 ** attempt))
                print(f"[wiki] response error: {exc}", file=sys.stderr)
                continue

            error = data.get("error") or {}
            if error.get("code") in {"maxlag", "ratelimited"}:
                time.sleep(8 * (2 ** attempt))
                continue
            return data
        return None

    def wikimedia(self, item: dict) -> list[dict]:
        params = {
            "action": "query",
            "generator": "search",
            "gsrsearch": short_query(item),
            "gsrnamespace": 6,
            "gsrlimit": min(self.per_provider, 50),
            "prop": "imageinfo",
            "iiprop": "url|size|extmetadata|mime",
            "iiurlwidth": 1800,
            "format": "json",
            "formatversion": 2,
        }
        data = self._wikimedia_get(params)
        if not data:
            return []

        out = []
        for page in ((data.get("query") or {}).get("pages") or []):
            infos = page.get("imageinfo") or []
            if not infos:
                continue
            info = infos[0]
            ext = info.get("extmetadata") or {}
            em = lambda key: clean((ext.get(key) or {}).get("value"))
            out.append({
                "provider": "wikimedia",
                "title": clean(str(page.get("title", "")).replace("File:", "")),
                "description": em("ImageDescription"),
                "image_url": info.get("thumburl") or info.get("url", ""),
                "page_url": info.get("descriptionurl", ""),
                "creator": em("Artist") or em("Credit"),
                "license": em("LicenseShortName") or "Wikimedia Commons",
                "license_url": em("LicenseUrl"),
                "categories": em("Categories"),
                "mime": info.get("mime", ""),
            })
        return out

    @staticmethod
    def bad_metadata(candidate: dict) -> bool:
        haystack = " ".join(
            clean(candidate.get(key)) for key in ("title", "description", "categories", "page_url")
        ).lower()
        if any(term in haystack for term in AI_TERMS | NONPHOTO_TERMS):
            return True
        mime = candidate.get("mime")
        return bool(mime and mime not in {"image/jpeg", "image/png", "image/webp"})

    def fetch_candidate(self, candidate: dict) -> dict | None:
        try:
            with self.session.get(candidate["image_url"], timeout=self.timeout, stream=True) as response:
                response.raise_for_status()
                chunks = []
                total = 0
                for chunk in response.iter_content(256 * 1024):
                    if not chunk:
                        continue
                    total += len(chunk)
                    if total > self.max_download_bytes:
                        return None
                    chunks.append(chunk)
                blob = b"".join(chunks)

            if len(blob) < 20_000:
                return None
            sha256 = hashlib.sha256(blob).hexdigest()
            if sha256 in self.used_sha:
                return None

            with Image.open(io.BytesIO(blob)) as image:
                image = ImageOps.exif_transpose(image).convert("RGB")
                width, height = image.size
                if width < 900 or height < 560:
                    return None

                phash = imagehash.phash(image)
                if any(phash - old <= self.phash_distance for old in self.used_phash):
                    return None

                target_ratio = 16 / 10
                if width / height > target_ratio:
                    crop_width = int(height * target_ratio)
                    left = (width - crop_width) // 2
                    review_image = image.crop((left, 0, left + crop_width, height))
                else:
                    crop_height = int(width / target_ratio)
                    top = (height - crop_height) // 2
                    review_image = image.crop((0, top, width, top + crop_height))
                if review_image.width > 1600:
                    review_image = review_image.resize((1600, 1000), Image.Resampling.LANCZOS)

                review_bytes = io.BytesIO()
                review_image.save(review_bytes, "JPEG", quality=88, optimize=True, progressive=True)

                source_image = image
                if source_image.width > 1800:
                    new_height = round(source_image.height * (1800 / source_image.width))
                    source_image = source_image.resize((1800, new_height), Image.Resampling.LANCZOS)
                source_bytes = io.BytesIO()
                source_image.save(source_bytes, "JPEG", quality=90, optimize=True, progressive=True)

            return {
                "sha256": sha256,
                "phash": phash,
                "width": width,
                "height": height,
                "review_bytes": review_bytes.getvalue(),
                "source_bytes": source_bytes.getvalue(),
            }
        except Exception:
            return None

    def accept_pool(self, item: dict, pool: list[dict], accepted: int) -> int:
        for candidate in pool:
            if accepted >= self.per_item:
                break
            if self.bad_metadata(candidate):
                continue
            downloaded = self.fetch_candidate(candidate)
            if not downloaded:
                continue

            accepted += 1
            self.used_sha.add(downloaded["sha256"])
            self.used_phash.append(downloaded["phash"])

            base = f"{item['id']:03d}-{slug(item['name'])}-{accepted:02d}"
            review_name = base + ".jpg"
            source_name = base + "-source.jpg"
            (self.images_dir / review_name).write_bytes(downloaded["review_bytes"])
            (self.sources_dir / source_name).write_bytes(downloaded["source_bytes"])

            self.records.append({
                "item_id": item["id"],
                "item_name": item["name"],
                "candidate": accepted,
                "file": "images/" + review_name,
                "source_original": "source_originals/" + source_name,
                "provider": candidate["provider"],
                "title": candidate.get("title", ""),
                "creator": candidate.get("creator", ""),
                "source_page": candidate.get("page_url", ""),
                "direct_image_url": candidate.get("image_url", ""),
                "license": candidate.get("license", ""),
                "license_url": candidate.get("license_url", ""),
                "width": downloaded["width"],
                "height": downloaded["height"],
                "sha256": downloaded["sha256"],
                "phash": str(downloaded["phash"]),
                "search_query": item["prompt"],
                "review_note": (
                    "Obvious AI/art/vector metadata terms rejected; exact SHA and global perceptual "
                    "near-duplicates rejected. Human visual and rights review still required."
                ),
            })
        return accepted

    def process_item(self, item: dict) -> int:
        accepted = 0

        # Pass 1: Pexels + one Google Images search.
        pool = []
        try:
            pool.extend(self.pexels(item))
        except Exception as exc:
            print(f"[warn] Pexels failed for {item['name']}: {exc}", file=sys.stderr)
        pool.extend(self.serpapi("google_images", item))
        accepted = self.accept_pool(item, pool, accepted)

        # Pass 2: respectful Wikimedia fallback.
        if accepted < self.per_item:
            accepted = self.accept_pool(item, self.wikimedia(item), accepted)

        # Pass 3: Bing as final backfill.
        if accepted < self.per_item:
            accepted = self.accept_pool(item, self.serpapi("bing_images", item), accepted)

        print(
            f"{item['id']:03d}. {item['name']}: {accepted}/{self.per_item} | "
            f"SerpApi {self.serpapi_used}/{self.serpapi_max} | Wikimedia {self.wikimedia_requests}"
        )
        return accepted

    def finish(self, items: list[dict]) -> dict:
        if self.records:
            with (self.output / "manifest.csv").open("w", newline="", encoding="utf-8-sig") as handle:
                writer = csv.DictWriter(handle, fieldnames=list(self.records[0].keys()))
                writer.writeheader()
                writer.writerows(self.records)
        (self.output / "manifest.json").write_text(
            json.dumps(self.records, indent=2, ensure_ascii=False), encoding="utf-8"
        )

        counts = {item["id"]: 0 for item in items}
        for record in self.records:
            counts[record["item_id"]] += 1
        summary = {
            "items": len(items),
            "target_per_item": self.per_item,
            "target_total": len(items) * self.per_item,
            "actual_total": len(self.records),
            "counts": counts,
            "complete": all(value == self.per_item for value in counts.values()),
            "serpapi_searches_used": self.serpapi_used,
            "serpapi_search_cap": self.serpapi_max,
            "wikimedia_api_requests": self.wikimedia_requests,
            "strategy": "Pexels + Google first; Wikimedia throttled fallback; Bing final backfill.",
        }
        (self.output / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

        sections = []
        markdown = [
            "# Image Review Pack", "",
            f"Target: {summary['target_total']}",
            f"Actual: {summary['actual_total']}",
            f"SerpApi searches: {summary['serpapi_searches_used']}",
            f"Wikimedia API requests: {summary['wikimedia_api_requests']}", "",
        ]
        for item in items:
            rows = [record for record in self.records if record["item_id"] == item["id"]]
            markdown.append(f"## {item['id']:03d}. {item['name']} — {len(rows)}/{self.per_item}")
            cards = []
            for record in rows:
                markdown.append(
                    f"- {record['candidate']}: `{record['file']}` — {record['provider']} — "
                    f"{record['license']} — {record['source_page']}"
                )
                cards.append(
                    f"<article><img src='{html.escape(record['file'])}'><b>Candidate {record['candidate']}</b>"
                    f"<small>{html.escape(record['provider'])}</small>"
                    f"<small>{html.escape(record['license'] or 'verify rights')}</small>"
                    f"<a href='{html.escape(record['source_page'])}' target='_blank'>Source</a></article>"
                )
            markdown.append("")
            sections.append(
                f"<section><h2>{item['id']:03d}. {html.escape(item['name'])} — {len(rows)}/{self.per_item}</h2>"
                f"<div class='grid'>{''.join(cards)}</div></section>"
            )

        (self.output / "DESCRIPTIONS.md").write_text("\n".join(markdown), encoding="utf-8")
        css = (
            "body{font-family:Arial,sans-serif;background:#eee;margin:20px;color:#171717}"
            "section{background:#fff;padding:16px;margin:16px 0;border-radius:10px}"
            ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}"
            "article{border:1px solid #ddd;padding:8px}img{width:100%;aspect-ratio:16/10;object-fit:cover}"
            "b,small,a{display:block;margin-top:4px}"
        )
        (self.output / "CONTACT_SHEET.html").write_text(
            f"<!doctype html><meta charset='utf-8'><style>{css}</style><h1>Image Review Pack</h1>"
            + "".join(sections),
            encoding="utf-8",
        )
        return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Harvest globally unique real-photo candidates from multiple providers.")
    parser.add_argument("prompts", type=Path, help="JSON prompt file")
    parser.add_argument("--output", type=Path, default=Path("image_review_pack"))
    parser.add_argument("--per-item", type=int, default=8)
    parser.add_argument("--per-provider", type=int, default=25)
    parser.add_argument("--near-duplicate-hamming", type=int, default=8)
    parser.add_argument("--serpapi-max-searches", type=int, default=int(os.getenv("SERPAPI_MAX_SEARCHES", "110")))
    parser.add_argument("--max-download-mb", type=int, default=25)
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    parser.add_argument("--keep-existing-output", action="store_true", help="Refuse to delete an existing output directory.")
    args = parser.parse_args()

    output = args.output.resolve()
    cwd = Path.cwd().resolve()
    home = Path.home().resolve()
    dangerous = {Path("/").resolve(), cwd, home, home.parent.resolve()}
    if os.name == "nt":
        dangerous.add(Path(output.anchor).resolve())
    if output in dangerous:
        raise SystemExit(f"Refusing dangerous output path: {output}")
    if output.exists():
        if args.keep_existing_output:
            raise SystemExit(f"Output already exists: {output}")
        shutil.rmtree(output)

    items = load_items(args.prompts)
    harvester = Harvester(
        output=output,
        per_item=args.per_item,
        per_provider=args.per_provider,
        phash_distance=args.near_duplicate_hamming,
        serpapi_max=args.serpapi_max_searches,
        max_download_mb=args.max_download_mb,
        timeout=args.timeout,
    )
    for item in items:
        harvester.process_item(item)

    summary = harvester.finish(items)
    zip_path = output.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in output.rglob("*"):
            if path.is_file():
                archive.write(path, path.relative_to(output.parent))

    print(json.dumps(summary, indent=2))
    print(f"ZIP: {zip_path}")
    return 0 if summary["complete"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
